# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    app.owner_email: '%env(CONTACT_OWNER_EMAIL)%'
    app.mail_from: '%env(MAIL_FROM)%'
    app.mail_from_name: '%env(MAIL_FROM_NAME)%'

    app.openrouter.api_key: '%env(OPENROUTER_API_KEY)%'
    app.openrouter.api_url: '%env(OPENROUTER_BASE_URL)%'
    app.openrouter.model: '%env(OPENROUTER_MODEL)%'

    # временно дефолты для dev
    app.openrouter.timeout: 30
    app.openrouter.fallback_reply: 'Спасибо за ваше сообщение. Мы скоро свяжемся с вами.'


services:
    _defaults:
        autowire: true
        autoconfigure: true


    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Dto/'
            - '../src/Kernel.php'


    App\Service\ContactMailerService:
        arguments:
            $ownerEmail: '%app.owner_email%'
            $mailFrom: '%app.mail_from%'
            $mailFromName: '%app.mail_from_name%'
            $fallbackReply: '%app.openrouter.fallback_reply%'


    App\EventSubscriber\ExceptionSubscriber:
        arguments:
            $environment: '%kernel.environment%'

when@test:
    services:
        _defaults:
            public: true
